packages:
  - "packages/*"
  - "create-app"
  #- "samples/*"

overrides:
  "@o3co/js.function-framework.core": "workspace:*"
  "@o3co/js.function-framework.node": "workspace:*"
  "@o3co/js.function-framework.lambda": "workspace:*"