storages: null 
clients: null
processes: null
commands:
  Echo:
    representer: null
  #  className: null
  #  process: null
  #  params:
  #    message: null
runtime:
  command: null
  response: pass 
