storages: null 
clients: null
processes: null
commands:
  Echo:
    #representer: null
    response: 
      type: static 
      return: '{"statusCode": 200}'
  #  className: null
  #  process: null
  #  params:
  #    message: null
runtime:
  command: null
  #response: 
  #  type: static 
  #  response: '{"statusCode": 200}'
